url_shortener/routes.py
from flask import Blueprint, render_template, request, redirect
from .extensions import db
from .models import Link


shortener = Blueprint('shortener', __name__)

@shortener.route('/<short_url>')
def redirect_to_url(short_url):
    # Implement logic to redirect to the original URL associated with the 'shorten_url'
    return ""

@shortener.route('/create_link', methods=['POST'])  # Added missing slash in the route URL
def create_link():
    # Implement logic to create and store a new shortened URL
    original_url = request.form['original_url']
    link=Link(original_url=original_url)
    db.session.add(link)
    db.session.commit()
    
    return render_template('link_success.html', 
        new_url=link.short_url,original_url=link.original_url)


@shortener.route('/')
def index():
    return render_template('index.html')

@shortener.route('/analytics')
def analytics():
    # Implement logic to show analytics for shortened URLs
    return ""

@shortener.errorhandler(404)
def page_not_found(e):
    return '<h1>Page not found 404</h1>', 404  # Fixed the syntax error in this line

url_shortener/templates/index.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<form method="POST" action="{{ url_for('shortener.create_link') }}" style="max-width: 800px; margin :50px;">
    <div class ="form-group">
        <label for ="original-url" style ="font-size : 28px;">
            Original URL
        </label>
        <input type="text" class ="form-control" placeholder="Enter URL" name="original-url" />
    </div>
    <button type="submit" class="btn btn-primary"> Submit</button>
    </form>